output_screen: true
is_save: false
label: 1
description_filename: description_1.csv

#description_parameter(if you change these parameter, you need to make a dataset again.)
intensity_histgram_limit: 3000
intensity_histgram_bin: 25
slice_sectors: 10
