output_screen: false
is_save: false
description_filename: description.csv

#description_parameter(if you change these parameter, you need to make a dataset again.)
intensity_histgram_limit: 3000
intensity_histgram_bin: 25
slice_sectors: 10
